<?php
/**
 * Created by PhpStorm.
 * User: Joel Salgado
 * Date: 12/03/2018
 * Time: 09:42 AM
 */

namespace common\behaviors;

use yii\behaviors\AttributeBehavior;
use yii\db\BaseActiveRecord;

class AuthKeyBehavior extends AttributeBehavior
{
    public $authKey = 'auth_key';

    public $value;

    public function init()
    {
        parent::init();
        if (empty($this->attributes)) {
            $this->attributes = [
                BaseActiveRecord::EVENT_BEFORE_INSERT => [$this->authKey]
            ];
        }
    }

    public function getValue($event)
    {
        if ($this->value === null) {
            return \Yii::$app->security->generateRandomString();
        }
        return parent::getValue($event); // TODO: Change the autogenerated stub
    }
}